<template>
  <tp-page class="tp-legal-page">
    <h1>Terms of Service</h1>
    <p class="paragraph tp-legal-page__updated">Last updated: {{ lastUpdated }}</p>

    <section>
      <h2>1. Acceptance of Terms</h2>
      <p class="paragraph">
        By accessing or using ToxiPred ("<strong>the Service</strong>"), you agree to be bound by these Terms
        of Service ("<strong>Terms</strong>"). If you do not agree, do not use the Service. We may update these
        Terms at any time; continued use after changes constitutes acceptance.
      </p>
    </section>

    <section>
      <h2>2. Description of Service</h2>
      <p class="paragraph">
        ToxiPred is a free, publicly accessible research platform that uses QSAR (Quantitative Structure–Activity
        Relationship) models to predict dermatological toxicity of chemical compounds. The Service is developed and
        maintained at the Slovak University of Technology in Bratislava (STU) for research and educational purposes.
      </p>
      <p class="paragraph">The Service allows you to:</p>
      <ul>
        <li>Submit chemical identifiers (SMILES strings, CAS numbers, or trivial names) for toxicity prediction.</li>
        <li>View prediction results including classification, confidence scores, and feature-level explanations.</li>
        <li>Store prediction history locally in your browser.</li>
        <li>Share prediction results with others via time-limited links.</li>
        <li>Draw molecular structures using an integrated editor.</li>
      </ul>
    </section>

    <section>
      <h2>3. Research Use Only — No Regulatory Reliance</h2>
      <div class="tp-legal-page__warning">
        <p class="paragraph bold">
          ToxiPred predictions are intended for research screening and educational purposes only.
        </p>
      </div>
      <p class="paragraph">
        The predictions generated by this Service are based on computational (in silico) QSAR models and
        <strong>must not</strong> be used as a sole basis for:
      </p>
      <ul>
        <li>Regulatory submissions or compliance decisions (e.g., REACH, CLP, FDA, EPA).</li>
        <li>Clinical, diagnostic, or therapeutic decision-making.</li>
        <li>Product safety assessments without independent experimental verification.</li>
        <li>Any decision where human health or safety depends on the accuracy of the prediction.</li>
      </ul>
      <p class="paragraph">
        While our models are OECD-aligned and validated, computational predictions carry inherent
        uncertainty. A prediction of "non-toxic" does <strong>not</strong> guarantee that a compound is safe,
        and a prediction of "toxic" does <strong>not</strong> constitute a definitive toxicological finding.
        Always corroborate computational results with appropriate experimental testing.
      </p>
    </section>

    <section>
      <h2>4. Acceptable Use</h2>
      <p class="paragraph">You agree to use ToxiPred only for lawful purposes. You must not:</p>
      <ul>
        <li>Attempt to reverse-engineer, decompile, or extract the underlying QSAR models or training data.</li>
        <li>Use automated scripts, bots, or scrapers to submit bulk queries that exceed reasonable use or
          degrade service availability for others.</li>
        <li>Attempt to gain unauthorized access to our servers, databases, or internal systems.</li>
        <li>Use the Service to facilitate the development of chemical, biological, or nuclear weapons, or any
          substance intended to cause harm to humans, animals, or the environment.</li>
        <li>Circumvent or interfere with any security measures, rate limits, or access controls.</li>
        <li>Misrepresent ToxiPred predictions as experimentally validated results.</li>
        <li>Use the Service in any manner that violates applicable local, national, or international law.</li>
      </ul>
    </section>

    <section>
      <h2>5. Intellectual Property</h2>
      <h3>5.1 Our Content</h3>
      <p class="paragraph">
        The ToxiPred platform, including its design, logos, source code, QSAR models, documentation, and all
        original content, is the intellectual property of the ToxiPred team and STU. All rights are reserved
        unless otherwise stated.
      </p>
      <h3>5.2 Your Submissions</h3>
      <p class="paragraph">
        Chemical structures and identifiers you submit remain your own. We do not claim ownership of your
        input data. We process your submissions solely to provide predictions and do not use them for model
        training or any other purpose.
      </p>
      <h3>5.3 Prediction Results</h3>
      <p class="paragraph">
        You are free to use, cite, and incorporate ToxiPred prediction results in your research, publications,
        and internal decision-making, provided you acknowledge the computational nature and limitations
        of the predictions. We encourage citing ToxiPred as the source when publishing results derived from
        this platform.
      </p>
    </section>

    <section>
      <h2>6. Disclaimer of Warranties</h2>
      <p class="paragraph">
        THE SERVICE IS PROVIDED "<strong>AS IS</strong>" AND "<strong>AS AVAILABLE</strong>" WITHOUT WARRANTIES
        OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF
        MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, COMPLETENESS, OR NON-INFRINGEMENT.
      </p>
      <p class="paragraph">Without limiting the foregoing, we do not warrant that:</p>
      <ul>
        <li>Predictions will be accurate, complete, or reliable for any specific compound or use case.</li>
        <li>The Service will be uninterrupted, error-free, or free from security vulnerabilities.</li>
        <li>Results will be suitable for any regulatory, clinical, or commercial purpose.</li>
        <li>Defects will be corrected in any particular timeframe.</li>
      </ul>
    </section>

    <section>
      <h2>7. Limitation of Liability</h2>
      <p class="paragraph">
        TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL TOXIPRED, ITS DEVELOPERS,
        CONTRIBUTORS, OR THE SLOVAK UNIVERSITY OF TECHNOLOGY IN BRATISLAVA BE LIABLE FOR ANY INDIRECT,
        INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO:
      </p>
      <ul>
        <li>Loss of profits, data, or business opportunities.</li>
        <li>Personal injury, property damage, or environmental harm arising from reliance on predictions.</li>
        <li>Costs of procuring substitute services.</li>
        <li>Any damages arising from unauthorized access to or alteration of your data in transit.</li>
      </ul>
      <p class="paragraph">
        This limitation applies regardless of the legal theory (contract, tort, strict liability, or otherwise)
        and whether or not we have been advised of the possibility of such damages.
      </p>
    </section>

    <section>
      <h2>8. Indemnification</h2>
      <p class="paragraph">
        You agree to indemnify, defend, and hold harmless ToxiPred, its developers, and the Slovak University
        of Technology in Bratislava from any claims, damages, losses, liabilities, costs, or expenses
        (including reasonable legal fees) arising from:
      </p>
      <ul>
        <li>Your use of the Service or reliance on any predictions.</li>
        <li>Your violation of these Terms.</li>
        <li>Your violation of any applicable law or regulation.</li>
        <li>Any harm caused to third parties resulting from your use of prediction results.</li>
      </ul>
    </section>

    <section>
      <h2>9. Service Availability</h2>
      <p class="paragraph">
        We strive to maintain continuous availability but do not guarantee uptime. We may modify, suspend, or
        discontinue the Service (in whole or in part) at any time without prior notice. We are not liable for
        any modification, suspension, or discontinuance.
      </p>
    </section>

    <section>
      <h2>10. Data Retention &amp; Deletion</h2>
      <p class="paragraph">
        Prediction results stored on our servers are automatically deleted after 14 days. Share links expire
        after 30 days. Local browser data (job history, preferences) persists until you clear it. See our
        <router-link to="/privacy-policy">Privacy Policy</router-link> for full details.
      </p>
    </section>

    <section>
      <h2>11. Links to Other Resources</h2>
      <p class="paragraph">
        The Service may contain links to external websites or resources (e.g., chemical databases, literature
        references). We are not responsible for the content, privacy practices, or availability of any external
        sites and do not endorse them.
      </p>
    </section>

    <section>
      <h2>12. Governing Law &amp; Jurisdiction</h2>
      <p class="paragraph">
        These Terms are governed by and construed in accordance with the laws of the Slovak Republic. Any
        disputes arising from or relating to these Terms or the Service shall be subject to the exclusive
        jurisdiction of the courts of Bratislava, Slovak Republic.
      </p>
    </section>

    <section>
      <h2>13. Severability</h2>
      <p class="paragraph">
        If any provision of these Terms is held to be invalid or unenforceable, the remaining provisions
        shall continue in full force and effect. The invalid provision shall be modified to the minimum extent
        necessary to make it valid and enforceable.
      </p>
    </section>

    <section>
      <h2>14. Entire Agreement</h2>
      <p class="paragraph">
        These Terms, together with our <router-link to="/privacy-policy">Privacy Policy</router-link>,
        <router-link to="/cookie-policy">Cookie Policy</router-link>, and
        <router-link to="/security">Security</router-link> page, constitute the entire agreement between you
        and ToxiPred regarding your use of the Service.
      </p>
    </section>

    <section>
      <h2>15. Contact</h2>
      <p class="paragraph">For questions about these Terms, contact us at:</p>
      <ul>
        <li><tp-link href="mailto:roganskyerik@gmail.com" label="roganskyerik@gmail.com" underline="hover" /></li>
        <li><tp-link href="mailto:marta.prnova@stuba.sk" label="marta.prnova@stuba.sk" underline="hover" /></li>
      </ul>
    </section>
  </tp-page>
</template>

<script setup lang="ts">
import TpPage from 'components/TpPage.vue';
import TpLink from 'components/TpLink.vue';

const lastUpdated = 'March 12, 2026';
</script>

<style scoped lang="scss">
@use 'src/css/helpers/mixins' as *;
@use 'src/css/helpers/glass' as glass;

.tp-legal-page {
  box-sizing: content-box;
  max-width: 750px;
  gap: 0;

  &__updated {
    color: var(--text-medium);
    margin-bottom: 32px;
  }

  &__warning {
    @include glass.glass-info-box();
    border-left: 4px solid var(--accent-yellow-regular);
    padding: 20px 24px;
    margin: 8px 0 16px;
  }

  section {
    margin-bottom: 32px;
  }

  h1 {
    margin-bottom: 8px;
  }

  h2 {
    margin-bottom: 12px;
    padding-top: 8px;
  }

  h3 {
    margin-top: 16px;
    margin-bottom: 8px;
  }

  p {
    margin-bottom: 12px;
    color: var(--text);
    line-height: 1.7;
  }

  ul {
    padding-left: 24px;
    margin-bottom: 12px;

    li {
      color: var(--text);
      line-height: 1.8;
      font-size: 16px;
    }
  }

  a {
    color: var(--text-brand-regular);
    text-decoration: none;

    &:hover {
      text-decoration: underline;
    }
  }
}
</style>
